# Generated by Django 5.0.6 on 2025-10-14 03:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True, verbose_name='Nombre')),
                ('logo', models.URLField(blank=True, verbose_name='Logo (URL)')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=30, unique=True, verbose_name='Patente')),
                ('model', models.CharField(blank=True, max_length=80, verbose_name='Modelo')),
                ('year', models.PositiveIntegerField(default=2024, verbose_name='Año')),
                ('floors', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='Pisos')),
                ('rows_upper', models.PositiveSmallIntegerField(default=0, verbose_name='Filas piso superior')),
                ('rows_lower', models.PositiveSmallIntegerField(default=10, verbose_name='Filas piso inferior')),
                ('cols', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Asientos por fila')),
                ('prefix_upper', models.CharField(blank=True, default='', max_length=5, verbose_name='Prefijo piso superior')),
                ('prefix_lower', models.CharField(blank=True, default='', max_length=5, verbose_name='Prefijo piso inferior')),
                ('layout_upper', models.JSONField(blank=True, default=list, verbose_name='Layout superior')),
                ('layout_lower', models.JSONField(blank=True, default=list, verbose_name='Layout inferior')),
                ('numbers_upper', models.JSONField(blank=True, default=list, verbose_name='Números superiores')),
                ('numbers_lower', models.JSONField(blank=True, default=list, verbose_name='Números inferiores')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.PositiveIntegerField(default=120, verbose_name='Duración (min)')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio base')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_to', to='booking.city', verbose_name='Destino')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_from', to='booking.city', verbose_name='Origen')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'unique_together': {('origin', 'destination')},
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck', models.PositiveSmallIntegerField(default=1, verbose_name='Piso')),
                ('row', models.PositiveSmallIntegerField(verbose_name='Fila')),
                ('position', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Posición')),
                ('number', models.CharField(max_length=10, verbose_name='Número')),
                ('is_window', models.BooleanField(default=False, verbose_name='Ventana')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='Ocupado')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='booking.bus', verbose_name='Bus')),
            ],
            options={
                'verbose_name': 'Asiento',
                'verbose_name_plural': 'Asientos',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.DateTimeField(verbose_name='Salida')),
                ('arrival', models.DateTimeField(verbose_name='Llegada')),
                ('seats_total', models.PositiveIntegerField(default=0, verbose_name='Asientos totales')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='booking.bus', verbose_name='Bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='booking.route', verbose_name='Ruta')),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='N° ticket')),
                ('buyer_name', models.CharField(max_length=140, verbose_name='Nombre pasajero')),
                ('national_id', models.CharField(blank=True, default='', max_length=40, verbose_name='Documento')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_sold', to=settings.AUTH_USER_MODEL)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='booking.seat')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='booking.trip')),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
            },
        ),
        migrations.CreateModel(
            name='SeatHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='booking.seat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seat_holds', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='booking.trip')),
            ],
            options={
                'verbose_name': 'Bloqueo temporal',
                'verbose_name_plural': 'Bloqueos temporales',
            },
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('bus', 'deck', 'number'), name='uniq_seat_per_bus_deck_number'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['trip'], name='booking_tic_trip_id_a8e210_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at'], name='booking_tic_created_d29b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='seathold',
            index=models.Index(fields=['trip', 'seat'], name='booking_sea_trip_id_80e73c_idx'),
        ),
        migrations.AddIndex(
            model_name='seathold',
            index=models.Index(fields=['active'], name='booking_sea_active_ab7a16_idx'),
        ),
        migrations.AddIndex(
            model_name='seathold',
            index=models.Index(fields=['expires_at'], name='booking_sea_expires_2b4402_idx'),
        ),
    ]
