# Generated by Django 5.0.6 on 2025-10-18 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'ordering': ('plate',), 'verbose_name': 'Bus', 'verbose_name_plural': 'Buses'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('name',), 'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('name',), 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ('origin__name', 'destination__name'), 'verbose_name': 'Ruta', 'verbose_name_plural': 'Rutas'},
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ('bus__plate', 'deck', 'row', 'position'), 'verbose_name': 'Asiento', 'verbose_name_plural': 'Asientos'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('-created_at',), 'verbose_name': 'Boleto', 'verbose_name_plural': 'Boletos'},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ('-departure',), 'verbose_name': 'Viaje', 'verbose_name_plural': 'Viajes'},
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='position',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=1, verbose_name='Posición'),
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Nombre')),
                ('address', models.CharField(blank=True, default='', max_length=200, verbose_name='Dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminals', to='booking.city', verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Terminal',
                'verbose_name_plural': 'Terminales',
                'ordering': ('city__name', 'name'),
                'unique_together': {('city', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='route',
            name='destination_terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes_to', to='booking.terminal', verbose_name='Terminal destino'),
        ),
        migrations.AddField(
            model_name='route',
            name='origin_terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes_from', to='booking.terminal', verbose_name='Terminal origen'),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('origin', 'destination', 'origin_terminal', 'destination_terminal')},
        ),
    ]
