# Generated by Django 5.0.6 on 2025-10-19 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_bus_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nombre del mapa')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('floors', models.PositiveSmallIntegerField(default=1)),
                ('rows_lower', models.PositiveSmallIntegerField(default=0)),
                ('rows_upper', models.PositiveSmallIntegerField(default=0)),
                ('cols', models.PositiveSmallIntegerField(default=4)),
                ('layout_lower', models.JSONField(blank=True, default=list)),
                ('layout_upper', models.JSONField(blank=True, default=list)),
                ('numbers_lower', models.JSONField(blank=True, default=list)),
                ('numbers_upper', models.JSONField(blank=True, default=list)),
                ('prefix_lower', models.CharField(blank=True, default='', max_length=10)),
                ('prefix_upper', models.CharField(blank=True, default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mapa de bus',
                'verbose_name_plural': 'Mapas de bus',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='bus',
            name='layout_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.buslayout', verbose_name='Mapa (plantilla)'),
        ),
    ]
