# Generated by Django 5.2.7 on 2025-10-28 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_buslayout_bus_layout_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Fecha')),
                ('total_tickets', models.PositiveIntegerField(default=0, verbose_name='Total boletos')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ingresos totales')),
                ('routes_sold', models.JSONField(default=dict, verbose_name='Rutas vendidas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reporte Diario',
                'verbose_name_plural': 'Reportes Diarios',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha apertura')),
                ('closing_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha cierre')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo inicial')),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo final')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total ventas')),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('closed', 'Cerrada')], default='open', max_length=20, verbose_name='Estado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['-opening_date'],
            },
        ),
    ]
