# Generated by Django 5.2.7 on 2025-10-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_dailyreport_cashregister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreport',
            name='routes_sold',
        ),
        migrations.AddField(
            model_name='cashregister',
            name='total_tickets',
            field=models.PositiveIntegerField(default=0, verbose_name='Total boletos'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='total_cash_registers',
            field=models.PositiveIntegerField(default=0, verbose_name='Cajas abiertas'),
        ),
    ]
