# Generated by Django 5.2.7 on 2025-10-31 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='nombre',
            field=models.CharField(default='Terminal Principal', max_length=120, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje (%) — ej.: 2.50', max_digits=5, verbose_name='Porcentaje de comisión'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='max_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto en CLP — ej.: 1500.00', max_digits=7, verbose_name='Descuento máximo permitido'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('vendedor', 'Vendedor'), ('cajero', 'Cajero')], db_index=True, default='vendedor', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='booking_use_role_4d5782_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['is_active'], name='booking_use_is_acti_ce65b0_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['terminal'], name='booking_use_termina_d7904b_idx'),
        ),
    ]
