# Generated by Django 5.2.7 on 2025-11-04 21:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_terminal_nombre_alter_userprofile_commission_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('trip', 'seat'), name='uniq_ticket_trip_seat'),
        ),
    ]
