# Generated by Django 5.2.7 on 2025-12-27 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_customer_ticket_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta')], db_index=True, default='cash', max_length=10, verbose_name='Método de pago'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['payment_method'], name='booking_tic_payment_83025c_idx'),
        ),
    ]
