# Generated by Django 5.2.7 on 2026-05-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_seat_bus_alter_trip_bus_alter_trip_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('coordinator', 'Coordinador'), ('vendedor', 'Vendedor'), ('cajero', 'Cajero')], db_index=True, default='vendedor', max_length=20, verbose_name='Rol'),
        ),
    ]
