# Generated by Django 5.2.7 on 2026-05-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='seat_service',
            field=models.CharField(choices=[('semi_cama', 'Semi Cama'), ('cama', 'Cama'), ('ejecutivo', 'Ejecutivo')], default='semi_cama', max_length=20, verbose_name='Tipo de asiento'),
        ),
    ]
