# Generated by Django 5.2.7 on 2026-05-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_seat_seat_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='services_lower',
            field=models.JSONField(blank=True, default=list, verbose_name='Servicios inferiores'),
        ),
        migrations.AddField(
            model_name='bus',
            name='services_upper',
            field=models.JSONField(blank=True, default=list, verbose_name='Servicios superiores'),
        ),
    ]
