# Generated by Django 5.2.7 on 2026-05-06 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_bus_services_lower_bus_services_upper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=140, verbose_name='Nombre completo')),
                ('rut', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='RUT')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Auxiliar',
                'verbose_name_plural': 'Auxiliares',
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=140, verbose_name='Nombre completo')),
                ('rut', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='RUT')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono')),
                ('license_number', models.CharField(blank=True, max_length=30, verbose_name='N° Licencia')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Chofer',
                'verbose_name_plural': 'Choferes',
                'ordering': ('full_name',),
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='booking.assistant', verbose_name='Auxiliar'),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_as_driver1', to='booking.driver', verbose_name='Chofer principal'),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_as_driver2', to='booking.driver', verbose_name='Segundo chofer'),
        ),
    ]
