# Generated by Django 5.2.7 on 2026-05-08 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_assistant_driver_trip_assistant_trip_driver1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('technical', 'Revisión técnica'), ('insurance', 'Seguro'), ('permit', 'Permiso de circulación'), ('other', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('document_number', models.CharField(blank=True, max_length=50, verbose_name='Número documento')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Fecha emisión')),
                ('expiry_date', models.DateField(verbose_name='Fecha vencimiento')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('file', models.FileField(blank=True, null=True, upload_to='bus_docs/', verbose_name='Archivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='booking.bus')),
            ],
            options={
                'verbose_name': 'Documento de bus',
                'verbose_name_plural': 'Documentos de buses',
                'ordering': ('expiry_date',),
            },
        ),
        migrations.CreateModel(
            name='DriverDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('license', 'Licencia de conducir'), ('medical', 'Certificado médico'), ('background', 'Antecedentes'), ('other', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('document_number', models.CharField(blank=True, max_length=50, verbose_name='Número documento')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Fecha emisión')),
                ('expiry_date', models.DateField(verbose_name='Fecha vencimiento')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('file', models.FileField(blank=True, null=True, upload_to='driver_docs/', verbose_name='Archivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='booking.driver')),
            ],
            options={
                'verbose_name': 'Documento de chofer',
                'verbose_name_plural': 'Documentos de choferes',
                'ordering': ('expiry_date',),
            },
        ),
    ]
