# Generated by Django 5.2.7 on 2026-05-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_busdocument_driverdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='background_check_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento antecedentes'),
        ),
        migrations.AddField(
            model_name='driver',
            name='medical_cert_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento certificado médico'),
        ),
        migrations.AddField(
            model_name='driver',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/photos/', verbose_name='Foto'),
        ),
    ]
