# Generated by Django 5.2.7 on 2026-05-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_driver_background_check_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='assistant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='assistants/photos/', verbose_name='Foto'),
        ),
    ]
