# Generated by Django 5.2.7 on 2026-05-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_assistant_notes_assistant_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
    ]
