# Generated by Django 5.2.7 on 2026-05-15 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_route_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='Orden de la parada en la ruta (1,2,3...)', verbose_name='Orden')),
                ('extra_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio adicional')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Parada obligatoria')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Notas')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.city', verbose_name='Ciudad')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='booking.route')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.terminal', verbose_name='Terminal (opcional)')),
            ],
            options={
                'verbose_name': 'Parada intermedia',
                'verbose_name_plural': 'Paradas intermedias',
                'ordering': ['order'],
                'unique_together': {('route', 'order')},
            },
        ),
    ]
