# Generated by Django 5.2.7 on 2026-05-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_routestop'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='axles',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Ejes'),
        ),
        migrations.AddField(
            model_name='bus',
            name='bodywork',
            field=models.CharField(blank=True, max_length=50, verbose_name='Carrocería'),
        ),
        migrations.AddField(
            model_name='bus',
            name='brand',
            field=models.CharField(blank=True, max_length=80, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='bus',
            name='circulation_card',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Tarjeta de circulación'),
        ),
        migrations.AddField(
            model_name='bus',
            name='color',
            field=models.CharField(blank=True, max_length=100, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='bus',
            name='cylinders',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cantidad de cilindros'),
        ),
        migrations.AddField(
            model_name='bus',
            name='dry_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso seco (kg)'),
        ),
        migrations.AddField(
            model_name='bus',
            name='engine_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° Motor'),
        ),
        migrations.AddField(
            model_name='bus',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('Gasolina', 'Gasolina'), ('Diesel', 'Diesel'), ('Gas Licuado de Petróleo', 'GLP'), ('Eléctrico', 'Eléctrico')], default='Diesel', max_length=30, verbose_name='Tipo combustible'),
        ),
        migrations.AddField(
            model_name='bus',
            name='gross_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso bruto (kg)'),
        ),
        migrations.AddField(
            model_name='bus',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Altura (m)'),
        ),
        migrations.AddField(
            model_name='bus',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento seguro'),
        ),
        migrations.AddField(
            model_name='bus',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='bus',
            name='last_maintenance',
            field=models.DateField(blank=True, null=True, verbose_name='Último mantenimiento'),
        ),
        migrations.AddField(
            model_name='bus',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Longitud (m)'),
        ),
        migrations.AddField(
            model_name='bus',
            name='manufacturing_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año fabricación'),
        ),
        migrations.AddField(
            model_name='bus',
            name='owner_first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombres del propietario'),
        ),
        migrations.AddField(
            model_name='bus',
            name='owner_last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellidos del propietario'),
        ),
        migrations.AddField(
            model_name='bus',
            name='permit_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento permiso circulación'),
        ),
        migrations.AddField(
            model_name='bus',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='N° Serie (VIN)'),
        ),
        migrations.AddField(
            model_name='bus',
            name='service_type',
            field=models.CharField(blank=True, choices=[('semi_cama', 'Semi Cama'), ('cama', 'Cama'), ('ejecutivo', 'Ejecutivo'), ('rural', 'Rural')], default='semi_cama', max_length=30, verbose_name='Tipo servicio'),
        ),
        migrations.AddField(
            model_name='bus',
            name='technical_review_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento revisión técnica'),
        ),
        migrations.AddField(
            model_name='bus',
            name='total_passengers',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Total pasajeros'),
        ),
        migrations.AddField(
            model_name='bus',
            name='total_seats',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Total asientos'),
        ),
        migrations.AddField(
            model_name='bus',
            name='vehicle_class',
            field=models.CharField(blank=True, choices=[('BUS RURAL', 'BUS RURAL'), ('BUS URBANO', 'BUS URBANO'), ('OMNIBUS', 'OMNIBUS'), ('N3-CAMION', 'N3-CAMION'), ('OTRO', 'OTRO')], default='BUS RURAL', max_length=50, verbose_name='Clase'),
        ),
        migrations.AddField(
            model_name='bus',
            name='wheels_count',
            field=models.PositiveSmallIntegerField(default=6, verbose_name='Cantidad de ruedas'),
        ),
        migrations.AddField(
            model_name='bus',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ancho (m)'),
        ),
    ]
