# Generated by Django 5.2.7 on 2026-05-30 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_agency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='seathold',
            index=models.Index(fields=['trip'], name='booking_sea_trip_id_45c48b_idx'),
        ),
        migrations.AddIndex(
            model_name='seathold',
            index=models.Index(fields=['user'], name='booking_sea_user_id_8e4f96_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_by'], name='booking_tic_created_b3c9b9_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['customer'], name='booking_tic_custome_109c12_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['departure'], name='booking_tri_departu_f81a45_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['bus'], name='booking_tri_bus_id_23c7a2_idx'),
        ),
    ]
