# Generated by Django 5.2.7 on 2026-06-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_seathold_booking_sea_trip_id_45c48b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='checked_in',
            field=models.BooleanField(default=False, verbose_name='Embarcado'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora embarque'),
        ),
    ]
