# Generated by Django 5.2.7 on 2026-06-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_ticket_checked_in_ticket_checked_in_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('discount_type', models.CharField(choices=[('student', 'Estudiante'), ('senior', 'Adulto Mayor'), ('corporate', 'Corporativo'), ('promo', 'Promocional')], max_length=20, verbose_name='Tipo')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Ej: 15.00 para 15%', max_digits=5, verbose_name='Porcentaje descuento')),
                ('code', models.CharField(blank=True, help_text='Código promocional (opcional)', max_length=50, null=True, unique=True, verbose_name='Código')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Válido desde')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Válido hasta')),
                ('max_uses', models.IntegerField(default=0, help_text='0 = ilimitado', verbose_name='Usos máximos')),
                ('used_count', models.IntegerField(default=0, verbose_name='Usos realizados')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Descuento',
                'verbose_name_plural': 'Descuentos',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('start_date', models.DateField(verbose_name='Fecha inicio')),
                ('end_date', models.DateField(verbose_name='Fecha fin')),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Ej: 1.2 = +20%, 0.9 = -10%', max_digits=4, verbose_name='Multiplicador')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Temporada',
                'verbose_name_plural': 'Temporadas',
                'ordering': ['start_date'],
            },
        ),
    ]
