# Generated by Django 5.2.7 on 2026-06-01 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_discount_season'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Nº seguimiento')),
                ('sender_name', models.CharField(max_length=140, verbose_name='Remitente')),
                ('sender_phone', models.CharField(max_length=20, verbose_name='Teléfono remitente')),
                ('recipient_name', models.CharField(max_length=140, verbose_name='Destinatario')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='Teléfono destinatario')),
                ('recipient_rut', models.CharField(blank=True, default='', max_length=20, verbose_name='RUT destinatario')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=6, verbose_name='Peso (kg)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarifa')),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta')], default='cash', max_length=10, verbose_name='Método pago')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('delivered', 'Entregada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha entrega')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcels_created', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcels', to='booking.trip')),
            ],
            options={
                'verbose_name': 'Encomienda',
                'verbose_name_plural': 'Encomiendas',
                'ordering': ('-created_at',),
            },
        ),
    ]
