# Generated by Django 5.2.7 on 2026-06-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0026_parcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='current_mileage',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilometraje actual'),
        ),
        migrations.AddField(
            model_name='bus',
            name='fuel_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Consumo (L/100km)'),
        ),
        migrations.AddField(
            model_name='bus',
            name='last_fuel_mileage',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilometraje última carga'),
        ),
        migrations.AddField(
            model_name='bus',
            name='last_fuel_refill',
            field=models.DateField(blank=True, null=True, verbose_name='Última carga combustible'),
        ),
        migrations.AddField(
            model_name='bus',
            name='last_maintenance_mileage',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilometraje último mantenimiento'),
        ),
        migrations.AddField(
            model_name='bus',
            name='next_maintenance_mileage',
            field=models.PositiveIntegerField(default=0, verbose_name='Próximo mantenimiento (km)'),
        ),
    ]
