# Generated by Django 5.2.7 on 2026-06-01 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_bus_current_mileage_bus_fuel_consumption_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('preventive', 'Mantenimiento preventivo'), ('corrective', 'Mantenimiento correctivo')], max_length=20, verbose_name='Tipo')),
                ('date', models.DateField(verbose_name='Fecha mantenimiento')),
                ('mileage', models.PositiveIntegerField(verbose_name='Kilometraje al momento')),
                ('description', models.TextField(verbose_name='Descripción del trabajo')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo')),
                ('workshop', models.CharField(blank=True, max_length=200, verbose_name='Taller')),
                ('next_maintenance_km', models.PositiveIntegerField(default=0, help_text='Kilometraje sugerido para próximo mantenimiento', verbose_name='Próximo mantenimiento (km)')),
                ('technician', models.CharField(blank=True, max_length=100, verbose_name='Técnico responsable')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='booking.bus')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenances_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ('-date',),
            },
        ),
    ]
