# Generated by Django 5.2.7 on 2026-06-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0028_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='seathold',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
