# Generated by Django 5.2.7 on 2026-06-13 17:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0029_seathold_session_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Fecha en que se realizó la carga de combustible', verbose_name='Fecha de carga')),
                ('liters', models.DecimalField(decimal_places=2, help_text='Cantidad de combustible en litros', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Litros cargados')),
                ('cost', models.DecimalField(decimal_places=2, help_text='Monto total pagado por la carga', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo total')),
                ('mileage', models.PositiveIntegerField(help_text='Kilometraje del bus en el momento de la carga', verbose_name='Kilometraje al momento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre la carga (ej: estación de servicio, factura N°, etc.)', verbose_name='Observaciones')),
                ('invoice_number', models.CharField(blank=True, help_text='Número de factura o comprobante', max_length=50, verbose_name='N° Factura')),
                ('gas_station', models.CharField(blank=True, help_text='Nombre de la estación donde se realizó la carga', max_length=200, verbose_name='Estación de servicio')),
                ('fuel_type', models.CharField(blank=True, choices=[('Diesel', 'Diesel'), ('Gasolina 93', 'Gasolina 93'), ('Gasolina 95', 'Gasolina 95'), ('Gasolina 97', 'Gasolina 97'), ('GLP', 'GLP'), ('GNV', 'GNV'), ('Otro', 'Otro')], default='Diesel', max_length=30, verbose_name='Tipo de combustible')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_records', to='booking.bus', verbose_name='Bus')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_records_created', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Carga de combustible',
                'verbose_name_plural': 'Cargas de combustible',
                'ordering': ('-date', '-created_at'),
                'get_latest_by': 'date',
                'indexes': [models.Index(fields=['bus', 'date'], name='booking_fue_bus_id_0c9efb_idx'), models.Index(fields=['date'], name='booking_fue_date_9b3284_idx'), models.Index(fields=['bus'], name='booking_fue_bus_id_f2a9b4_idx')],
            },
        ),
    ]
