# Generated by Django 5.2.7 on 2026-06-16 03:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0030_fuelrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Código')),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed', 'Monto fijo')], default='percentage', max_length=20, verbose_name='Tipo descuento')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor descuento')),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto mínimo de compra')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Descuento máximo')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Válido desde')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Válido hasta')),
                ('max_uses', models.IntegerField(default=0, help_text='0 = ilimitado', verbose_name='Usos máximos')),
                ('used_count', models.IntegerField(default=0, verbose_name='Usos realizados')),
                ('max_uses_per_user', models.IntegerField(default=1, verbose_name='Usos por usuario')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_roles', models.ManyToManyField(blank=True, related_name='coupons', to='booking.userprofile')),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='Para usuarios no autenticados', max_length=100, null=True, verbose_name='Clave de sesión')),
                ('booking_id', models.PositiveIntegerField(blank=True, help_text='ID de la reserva/compra donde se usó el cupón', null=True, verbose_name='ID de reserva')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto descontado')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de uso')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='booking.coupon', verbose_name='Cupón')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Uso de cupón',
                'verbose_name_plural': 'Usos de cupones',
                'ordering': ['-used_at'],
                'indexes': [models.Index(fields=['coupon', 'used_at'], name='booking_cou_coupon__0e74e2_idx'), models.Index(fields=['session_key'], name='booking_cou_session_401fcd_idx'), models.Index(fields=['user'], name='booking_cou_user_id_5927e3_idx')],
            },
        ),
    ]
