# Generated by Django 5.2.7 on 2026-06-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_coupon_couponusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Código')),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed', 'Monto fijo')], default='percentage', max_length=20, verbose_name='Tipo descuento')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor descuento')),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto mínimo de compra')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Descuento máximo')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Válido desde')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Válido hasta')),
                ('max_uses', models.IntegerField(default=0, help_text='0 = ilimitado', verbose_name='Usos máximos')),
                ('used_count', models.IntegerField(default=0, verbose_name='Usos realizados')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-created_at'],
            },
        ),
    ]
