# Generated by Django 5.2.7 on 2026-06-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0033_migrate_promotion_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='applicable_roles',
        ),
        migrations.RemoveField(
            model_name='couponusage',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='couponusage',
            name='user',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.AlterField(
            model_name='fuelrecord',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas adicionales sobre la carga', verbose_name='Observaciones'),
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='CouponUsage',
        ),
    ]
