# Generated by Django 5.2.7 on 2026-07-05 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0035_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('coordinator', 'Coordinador'), ('vendedor', 'Vendedor'), ('cajero', 'Cajero'), ('convenio', 'Gestor de Convenios')], db_index=True, default='vendedor', max_length=20, verbose_name='Rol'),
        ),
        migrations.CreateModel(
            name='CompanyContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='N° Contrato')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Límite de crédito')),
                ('used_credit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Crédito utilizado')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento (%)')),
                ('valid_from', models.DateField(verbose_name='Válido desde')),
                ('valid_to', models.DateField(verbose_name='Válido hasta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('contact_name', models.CharField(blank=True, max_length=140, verbose_name='Nombre de contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de contacto')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='booking.company')),
            ],
            options={
                'verbose_name': 'Contrato de Convenio',
                'verbose_name_plural': 'Contratos de Convenio',
                'ordering': ['company__name', 'contract_number'],
            },
        ),
        migrations.CreateModel(
            name='ContractEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='ID Interno (empresa)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='booking.companycontract')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts_employee', to='booking.customer')),
            ],
            options={
                'verbose_name': 'Empleado Convenio',
                'verbose_name_plural': 'Empleados Convenio',
                'ordering': ['contract__company__name', 'customer__full_name'],
                'unique_together': {('contract', 'customer')},
            },
        ),
    ]
