# Generated by Django 5.2.7 on 2026-07-06 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0036_alter_userprofile_role_companycontract_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='booking.companycontract', verbose_name='Contrato de convenio'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_credit',
            field=models.BooleanField(default=False, verbose_name='¿Compra a crédito?'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('credit', 'Crédito Convenio')], default='cash', max_length=10, verbose_name='Método pago'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('credit', 'Crédito Convenio')], db_index=True, default='cash', max_length=10, verbose_name='Método de pago'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['contract'], name='booking_tic_contrac_9dd4d5_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['is_credit'], name='booking_tic_is_cred_c1cfeb_idx'),
        ),
    ]
