# Generated by Django 5.2.7 on 2026-07-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0037_ticket_contract_ticket_is_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cutoff_minutes',
            field=models.PositiveSmallIntegerField(default=10, help_text='Minutos antes de la salida en que se bloquea la compra en la web. 0 = sin restricción.', verbose_name='Corte de ventas web (min)'),
        ),
    ]
