# Generated by Django 5.2.7 on 2026-07-17 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0038_trip_cutoff_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('create', 'Creación'), ('update', 'Actualización'), ('delete', 'Eliminación'), ('view', 'Visualización'), ('export', 'Exportación'), ('login_failed', 'Intento de login fallido'), ('download_backup', 'Descarga de respaldo'), ('backup_created', 'Respaldo creado')], db_index=True, max_length=20)),
                ('model_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'user'], name='booking_aud_timesta_0ed58b_idx'), models.Index(fields=['action', 'timestamp'], name='booking_aud_action_052d4e_idx')],
            },
        ),
    ]
