# Generated by Django 5.2.7 on 2026-07-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0040_add_ticket_number_seq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
