# Generated by Django 5.2.7 on 2026-08-11 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0041_alter_auditlog_object_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='seathold',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='seathold',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seat_holds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='seathold',
            index=models.Index(fields=['session_key'], name='booking_sea_session_99b9c0_idx'),
        ),
        migrations.AddIndex(
            model_name='seathold',
            index=models.Index(fields=['trip', 'seat', 'active'], name='hold_trip_seat_active_idx'),
        ),
    ]
