# Generated by Django 5.2.7 on 2026-08-12 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0042_alter_seathold_active_alter_seathold_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=40, unique=True)),
                ('session_key', models.CharField(db_index=True, max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('payment_started', 'Pago iniciado'), ('paid', 'Pagada'), ('failed', 'Pago fallido'), ('cancelled', 'Cancelada'), ('expired', 'Expirada')], db_index=True, default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_orders', to='booking.customer')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_orders', to='booking.trip')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva web',
                'verbose_name_plural': 'Reservas web',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingOrderSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=150)),
                ('passenger_document', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='booking.bookingorder')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_order_items', to='booking.seat')),
            ],
            options={
                'verbose_name': 'Asiento de reserva',
                'verbose_name_plural': 'Asientos de reserva',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='transbank', max_length=30)),
                ('token', models.CharField(blank=True, db_index=True, max_length=255)),
                ('buy_order', models.CharField(db_index=True, max_length=50, unique=True)),
                ('session_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('created', 'Creada'), ('authorized', 'Autorizada'), ('rejected', 'Rechazada'), ('aborted', 'Abortada'), ('error', 'Error')], db_index=True, default='created', max_length=30)),
                ('authorization_code', models.CharField(blank=True, max_length=100)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='booking.bookingorder')),
            ],
            options={
                'verbose_name': 'Transacción de pago',
                'verbose_name_plural': 'Transacciones de pago',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bookingorder',
            index=models.Index(fields=['status', 'expires_at'], name='order_status_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingorder',
            index=models.Index(fields=['trip', 'status'], name='order_trip_status_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingorder',
            index=models.Index(fields=['session_key', 'status'], name='order_session_status_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingorderseat',
            index=models.Index(fields=['order', 'seat'], name='order_seat_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookingorderseat',
            constraint=models.UniqueConstraint(fields=('order', 'seat'), name='uniq_order_seat'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['order', 'status'], name='payment_order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['provider', 'status'], name='payment_provider_status_idx'),
        ),
    ]
