# Generated by Django 5.2.7 on 2026-08-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0043_bookingorder_bookingorderseat_paymenttransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingorder',
            name='buyer_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='bookingorder',
            name='buyer_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='bookingorder',
            name='buyer_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='bookingorder',
            name='buyer_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='bookingorder',
            name='discount_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bookingorderseat',
            name='passenger_document_type',
            field=models.CharField(default='RUT', max_length=20),
        ),
        migrations.AddField(
            model_name='bookingorderseat',
            name='passenger_lastname',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='bookingorderseat',
            name='passenger_nationality',
            field=models.CharField(default='CHI', max_length=10),
        ),
    ]
