# Generated by Django 5.2.7 on 2026-08-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0044_bookingorder_buyer_address_bookingorder_buyer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='license_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento licencia'),
        ),
    ]
