# Generated by Django 5.2.7 on 2026-08-28 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0045_driver_license_expiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='actual_arrival',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Llegada real'),
        ),
        migrations.AddField(
            model_name='trip',
            name='actual_departure',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Salida real'),
        ),
        migrations.AddField(
            model_name='trip',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_trips', to=settings.AUTH_USER_MODEL, verbose_name='Finalizado por'),
        ),
        migrations.AddField(
            model_name='trip',
            name='dispatched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_trips', to=settings.AUTH_USER_MODEL, verbose_name='Despachado por'),
        ),
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programado'), ('in_progress', 'En viaje'), ('completed', 'Finalizado')], db_index=True, default='scheduled', max_length=20, verbose_name='Estado operacional'),
        ),
    ]
