# Generated by Django 5.2.7 on 2026-08-28 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0046_trip_actual_arrival_trip_actual_departure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_type', models.CharField(choices=[('person', 'Persona natural'), ('company', 'Empresa / sociedad')], default='person', max_length=20, verbose_name='Tipo de propietario')),
                ('first_name', models.CharField(max_length=140, verbose_name='Nombres / razón social')),
                ('last_name', models.CharField(blank=True, default='', max_length=140, verbose_name='Apellidos')),
                ('rut', models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='RUT')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Teléfono')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_owners', to='booking.company', verbose_name='Empresa operadora')),
            ],
            options={
                'verbose_name': 'Propietario de flota',
                'verbose_name_plural': 'Propietarios de flota',
                'ordering': ('company__name', 'first_name', 'last_name'),
            },
        ),
        migrations.AddField(
            model_name='bus',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buses', to='booking.fleetowner', verbose_name='Propietario / socio'),
        ),
        migrations.AddIndex(
            model_name='fleetowner',
            index=models.Index(fields=['company', 'is_active'], name='booking_fle_company_e3123e_idx'),
        ),
        migrations.AddIndex(
            model_name='fleetowner',
            index=models.Index(fields=['rut'], name='booking_fle_rut_c47d2a_idx'),
        ),
        migrations.AddConstraint(
            model_name='fleetowner',
            constraint=models.UniqueConstraint(condition=models.Q(('rut', ''), _negated=True), fields=('company', 'rut'), name='uniq_fleet_owner_company_rut'),
        ),
    ]
