# Generated by Django 5.2.7 on 2026-08-29 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0047_fleetowner_bus_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_profiles', to='booking.company', verbose_name='Empresa operadora'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fleet_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_profiles', to='booking.fleetowner', verbose_name='Propietario / socio asociado'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('coordinator', 'Coordinador'), ('vendedor', 'Vendedor'), ('cajero', 'Cajero'), ('convenio', 'Gestor de Convenios'), ('owner', 'Propietario / Socio'), ('executive', 'Dueño / Gerencia'), ('secretary', 'Secretaria')], db_index=True, default='vendedor', max_length=20, verbose_name='Rol'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['company'], name='booking_use_company_b1f8bc_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['fleet_owner'], name='booking_use_fleet_o_d474a3_idx'),
        ),
    ]
