# Generated by Django 5.2.7 on 2026-08-30 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0048_userprofile_company_userprofile_fleet_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='revenue_bus',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revenue_tickets', to='booking.bus', verbose_name='Bus origen de la venta'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='revenue_owner',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revenue_tickets', to='booking.fleetowner', verbose_name='Propietario económico'),
        ),
    ]
