# Generated by Django 5.2.7 on 2026-09-01 04:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0049_ticket_revenue_bus_ticket_revenue_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Desde')),
                ('date_to', models.DateField(verbose_name='Hasta')),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Ventas brutas')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Comisión')),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Monto líquido')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('review', 'En revisión'), ('paid', 'Pagada'), ('cancelled', 'Anulada')], db_index=True, default='pending', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owner_settlements', to='booking.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owner_settlements_created', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='booking.fleetowner', verbose_name='Propietario / socio')),
            ],
            options={
                'verbose_name': 'Liquidación de propietario',
                'verbose_name_plural': 'Liquidaciones de propietarios',
                'ordering': ('-date_to', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='OwnerSettlementTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto del ticket')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='booking.ownersettlement', verbose_name='Liquidación')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='owner_settlement_item', to='booking.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Ticket liquidado',
                'verbose_name_plural': 'Tickets liquidados',
                'ordering': ('ticket__created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='ownersettlement',
            index=models.Index(fields=['company', 'owner'], name='booking_own_company_3b6809_idx'),
        ),
        migrations.AddIndex(
            model_name='ownersettlement',
            index=models.Index(fields=['status'], name='booking_own_status_688769_idx'),
        ),
        migrations.AddIndex(
            model_name='ownersettlement',
            index=models.Index(fields=['date_from', 'date_to'], name='booking_own_date_fr_32683e_idx'),
        ),
    ]
