# Generated by Django 5.2.7 on 2026-09-01 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0050_ownersettlement_ownersettlementticket_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ownersettlement',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ownersettlement',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownersettlement',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_owner_settlements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ownersettlement',
            name='cancelled_ticket_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
