# Generated by Django 5.2.7 on 2026-09-02 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0051_ownersettlement_cancellation_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerSettlementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('pending', 'Pendiente'), ('review', 'En revisión'), ('paid', 'Pagada'), ('cancelled', 'Anulada')], max_length=20)),
                ('new_status', models.CharField(choices=[('pending', 'Pendiente'), ('review', 'En revisión'), ('paid', 'Pagada'), ('cancelled', 'Anulada')], max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owner_settlement_status_changes', to=settings.AUTH_USER_MODEL)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='booking.ownersettlement')),
            ],
            options={
                'verbose_name': 'Historial de liquidación',
                'verbose_name_plural': 'Historial de liquidaciones',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['settlement', 'created_at'], name='booking_own_settlem_33c1f2_idx'), models.Index(fields=['new_status', 'created_at'], name='booking_own_new_sta_412103_idx')],
            },
        ),
    ]
