# Generated by Django 5.2.7 on 2026-09-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0052_ownersettlementhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buslayout',
            options={'ordering': ('name',), 'verbose_name': 'Plantilla de bus', 'verbose_name_plural': 'Plantillas de buses'},
        ),
        migrations.AddField(
            model_name='buslayout',
            name='background_lower',
            field=models.CharField(blank=True, default='', help_text='Ruta relativa dentro de static. Ejemplo: img/bus-generico.png', max_length=255, verbose_name='Fondo piso inferior'),
        ),
        migrations.AddField(
            model_name='buslayout',
            name='background_upper',
            field=models.CharField(blank=True, default='', help_text='Ruta relativa dentro de static. Ejemplo: img/bus-piso2.png', max_length=255, verbose_name='Fondo piso superior'),
        ),
        migrations.AddField(
            model_name='buslayout',
            name='editor_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Configuración visual del editor'),
        ),
        migrations.AddField(
            model_name='buslayout',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AddField(
            model_name='buslayout',
            name='is_system',
            field=models.BooleanField(default=False, help_text='Identifica plantillas base provistas por el sistema.', verbose_name='Plantilla del sistema'),
        ),
        migrations.AddField(
            model_name='buslayout',
            name='structure_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Configuración estructural'),
        ),
        migrations.AlterField(
            model_name='buslayout',
            name='cols',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='Columnas'),
        ),
        migrations.AlterField(
            model_name='buslayout',
            name='floors',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Pisos'),
        ),
        migrations.AlterField(
            model_name='buslayout',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Nombre de la plantilla'),
        ),
        migrations.AlterField(
            model_name='buslayout',
            name='rows_lower',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Filas piso inferior'),
        ),
        migrations.AlterField(
            model_name='buslayout',
            name='rows_upper',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Filas piso superior'),
        ),
    ]
