# Generated by Django 5.2.7 on 2026-09-06 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0053_alter_buslayout_options_buslayout_background_lower_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ('company__name', 'origin__name', 'destination__name'), 'verbose_name': 'Ruta', 'verbose_name_plural': 'Rutas'},
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='route',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='booking.company', verbose_name='Empresa'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('company', 'origin', 'destination', 'origin_terminal', 'destination_terminal')},
        ),
    ]
