# Generated by Django 5.2.7 on 2026-09-07 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0054_alter_route_options_alter_route_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assistants', to='booking.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='driver',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='booking.company', verbose_name='Empresa'),
        ),
    ]
