# Generated by Django 5.2.7 on 2026-09-07 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0055_assistant_company_driver_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assistants', to='booking.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='booking.company', verbose_name='Empresa'),
        ),
    ]
