# Generated by Django 5.2.7 on 2026-09-08 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0056_alter_assistant_company_alter_driver_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agencies', to='booking.company', verbose_name='Empresa'),
        ),
    ]
