# Generated by Django 5.2.7 on 2026-09-08 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0057_agency_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agencies', to='booking.company', verbose_name='Empresa'),
        ),
    ]
