# Generated by Django 5.2.7 on 2026-09-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0058_alter_agency_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'verbose_name': 'Agencia'},
        ),
        migrations.AlterField(
            model_name='agency',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nombre de la agencia'),
        ),
    ]
