# Generated by Django 5.2.7 on 2026-09-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0059_alter_agency_options_alter_agency_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ('name',), 'verbose_name': 'Agencia', 'verbose_name_plural': 'Agencias'},
        ),
        migrations.AddConstraint(
            model_name='agency',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_agency_name_per_company'),
        ),
    ]
