# Generated by Django 5.2.7 on 2026-09-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0061_seed_cejer_bus_layouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='accent_color',
            field=models.CharField(blank=True, default='#f5821f', help_text='Color hexadecimal. Ejemplo: #f5821f', max_length=7, verbose_name='Color de acento'),
        ),
        migrations.AddField(
            model_name='company',
            name='client_background',
            field=models.URLField(blank=True, default='', help_text='Opcional. Imagen corporativa para la pantalla del cliente.', verbose_name='Imagen Pantalla Cliente (URL)'),
        ),
        migrations.AddField(
            model_name='company',
            name='pos_background',
            field=models.URLField(blank=True, default='', help_text='Opcional. Imagen corporativa para el POS.', verbose_name='Imagen de fondo POS (URL)'),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_color',
            field=models.CharField(blank=True, default='#0f172a', help_text='Color hexadecimal. Ejemplo: #0f172a', max_length=7, verbose_name='Color principal'),
        ),
        migrations.AddField(
            model_name='company',
            name='secondary_color',
            field=models.CharField(blank=True, default='#1e293b', help_text='Color hexadecimal. Ejemplo: #1e293b', max_length=7, verbose_name='Color secundario'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.URLField(blank=True, default='', verbose_name='Logo (URL)'),
        ),
    ]
