# Generated by Django 5.2.7 on 2026-09-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0062_company_accent_color_company_client_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='client_background',
            field=models.ImageField(blank=True, help_text='Imagen corporativa utilizada en la segunda pantalla del cliente.', null=True, upload_to='companies/client_backgrounds/', verbose_name='Imagen Pantalla Cliente'),
        ),
        migrations.AlterField(
            model_name='company',
            name='pos_background',
            field=models.ImageField(blank=True, help_text='Imagen corporativa utilizada como fondo del POS.', null=True, upload_to='companies/pos_backgrounds/', verbose_name='Imagen de fondo POS'),
        ),
    ]
