# Generated by Django 5.2.7 on 2026-09-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0063_alter_company_client_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo corporativo de la empresa, preferentemente PNG con fondo transparente.', null=True, upload_to='companies/logos/', verbose_name='Logo de la empresa'),
        ),
    ]
