# Generated by Django 5.2.7 on 2026-09-14 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0064_alter_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='buslayout',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Empresa propietaria de la plantilla. Déjalo vacío para una plantilla genérica compartida.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bus_layouts', to='booking.company', verbose_name='Empresa'),
        ),
    ]
