# Generated by Django 5.2.7 on 2026-09-16 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0065_buslayout_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, help_text='Dominio público de la empresa, sin http:// ni https://. Ejemplo: portena.online', max_length=255, unique=True, verbose_name='Dominio')),
                ('is_primary', models.BooleanField(default=False, help_text='Indica si este es el dominio principal de la empresa.', verbose_name='Dominio principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='booking.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Dominio de empresa',
                'verbose_name_plural': 'Dominios de empresas',
                'ordering': ('company__name', 'domain'),
            },
        ),
    ]
