# Generated by Django 5.0.6 on 2026-09-30 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0066_companydomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_cities', to='booking.city', verbose_name='Ciudad')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_cities', to='booking.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Ciudad de empresa',
                'verbose_name_plural': 'Ciudades de empresas',
                'ordering': ('company__name', 'city__name'),
            },
        ),
        migrations.AddConstraint(
            model_name='companycity',
            constraint=models.UniqueConstraint(fields=('company', 'city'), name='unique_company_city'),
        ),
    ]
