# Generated by Django 5.0.6 on 2026-10-02 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0067_company_city_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_terminals', to='booking.company', verbose_name='Empresa')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_terminals', to='booking.terminal', verbose_name='Terminal')),
            ],
            options={
                'verbose_name': 'Terminal de empresa',
                'verbose_name_plural': 'Terminales de empresas',
                'ordering': ('company__name', 'terminal__city__name', 'terminal__name'),
            },
        ),
        migrations.AddConstraint(
            model_name='companyterminal',
            constraint=models.UniqueConstraint(fields=('company', 'terminal'), name='unique_company_terminal'),
        ),
    ]
