# Generated by Django 5.0.6 on 2026-10-03 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0068_companyterminal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='Orden dentro del viaje: 0, 1, 2, 3...', verbose_name='Orden')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora programada')),
                ('is_origin', models.BooleanField(default=False, verbose_name='Es origen')),
                ('is_destination', models.BooleanField(default=False, verbose_name='Es destino')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.city', verbose_name='Ciudad')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.terminal', verbose_name='Terminal / Paradero')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_stops', to='booking.trip', verbose_name='Viaje')),
            ],
            options={
                'verbose_name': 'Parada de viaje',
                'verbose_name_plural': 'Paradas de viaje',
                'ordering': ('order',),
                'indexes': [models.Index(fields=['trip', 'order'], name='trip_stop_order_idx'), models.Index(fields=['trip', 'city'], name='trip_stop_city_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tripstop',
            constraint=models.UniqueConstraint(fields=('trip', 'order'), name='unique_trip_stop_order'),
        ),
    ]
