# Generated by Django 5.0.6 on 2026-10-03 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0069_tripstop_tripstop_unique_trip_stop_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='seathold',
            name='alighting_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holds_alighting', to='booking.tripstop', verbose_name='Parada de bajada'),
        ),
        migrations.AddField(
            model_name='seathold',
            name='boarding_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holds_boarding', to='booking.tripstop', verbose_name='Parada de subida'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='alighting_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_alighting', to='booking.tripstop', verbose_name='Parada de bajada'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='boarding_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_boarding', to='booking.tripstop', verbose_name='Parada de subida'),
        ),
    ]
