# Generated by Django 5.0.6 on 2026-10-03 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0070_seathold_alighting_stop_seathold_boarding_stop_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='uniq_ticket_trip_seat',
        ),
    ]
