# Generated by Django 5.0.6 on 2026-10-04 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0071_remove_ticket_uniq_ticket_trip_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingorder',
            name='alighting_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_orders_alighting', to='booking.tripstop', verbose_name='Parada de bajada'),
        ),
        migrations.AddField(
            model_name='bookingorder',
            name='boarding_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_orders_boarding', to='booking.tripstop', verbose_name='Parada de subida'),
        ),
    ]
